### ISSUE TITLE
Better handling of nonspatial arrays, rois that are None

### ISSUE THREAD

**Issue by cmalinmayor** [funkelab/gunpowder#142]
Original issue: Batch.get_total_roi() kept throwing an error because it assumes every ArraySpec has a non-None Roi. For nonspatial arrays, this is not true. For spatial arrays, this SHOULD be true, but there are no checks (so when I forgot to mark an array as nonspatial, it gave me a confusing error that NoneType has no attribute get_begin()).

The ArraySpec documentation currently says that 1) roi can be none for BatchProviders that allow requests for arrays everywhere, but 2) will always be set for array specs that are part of an Array. 2) is not true for nonspatial arrays. 1) seems weird, because we have unbounded Rois to handle this case.

I'm not sure if the documentation is outdated, or if it still reflects the code accurately, but it seems like ArraySpecs should always have a roi that is not None, unless they are nonspatial. I'd propose adding this check to ArraySpec, and then handling the nonspatial case in functions like Batch.get_total_roi(), but a deeper dive is needed to make sure this doesn't break anything else like BatchProvider.

**Comment by pattonw** [comment]
addressed here: https://github.com/funkelab/gunpowder/commit/b557548bcfd73b09340ff61eca4d727e87f52446
