### ISSUE TITLE
Combination of RandomLocation and Reject provide repeated batches from the same source Roi

### ISSUE THREAD

**Issue by bentaculum** [funkelab/gunpowder#156]
A standard gunpowder pipeline with `RandomLocation` and `Reject` leads to consecutive batches that come from the exact same source Roi, supposedly due to a bug in `Reject`'s random seeding.

Below is a minimal example that showcases this.
Running with `logging.setLevel(logging.DEBUG)` sheds light at the problem in detail: Due to the fixed random seeding of requests, if `n` batches with Rois `r0, r1 ... rn-1` are rejected, `r1,r2, ..., rn-1` will be queried again in next request coming from downstream, leading to `n` consecutive identical Rois `rn` that are actually passed downstream by `Reject`.

I have implemented a quick fix by updating `request._random_seed` in `Reject`'s loop, which requests batches until a feasible one is found, by putting `request._random_seed += random.randint(0, 2**63 - 1)`in line 75 in `Reject` https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/gunpowder/nodes/reject.py#L75.
However, I do not fully understand how the request seeding is designed to work, so this is probably not the proper fix for this problem. Happy to discuss and then file a PR.

You might need to use gunpowder's master branch to run this without other errors.
```python
import logging

import numpy as np
from skimage.morphology import disk

import gunpowder as gp

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


class Source(gp.BatchProvider):
    """Toy source with a padded 2D disk, raw and labels array."""

    def __init__(self, raw_key, labels_key, voxel_size):

        self.voxel_size = voxel_size
        self.raw_key = raw_key
        self.labels_key = labels_key

        data = disk(64)
        data = np.pad(data, 96, mode='constant')

        roi = gp.Roi((0,) * 2, data.shape)

        # RAW
        noise = np.random.normal(0, 0.5, data.shape)
        raw = data + noise
        raw = raw.clip(0, None)
        raw = raw / raw.max()
        raw = (raw * 255).astype(np.uint8)

        self.raw_spec = gp.ArraySpec(
            roi=roi,
            voxel_size=self.voxel_size,
            dtype=raw.dtype,
            interpolatable=True
        )
        self.raw_array = gp.Array(raw, self.raw_spec)

        # LABELS
        labels = data
        self.labels_spec = gp.ArraySpec(
            roi=roi,
            voxel_size=self.voxel_size,
            dtype=np.uint8,
            interpolatable=False
        )
        self.labels_array = gp.Array(labels, self.labels_spec)

    def setup(self):

        self.provides(self.raw_key, self.raw_spec)
        self.provides(self.labels_key, self.labels_spec)

    def provide(self, request):

        out = gp.Batch()

        if self.raw_key in request:
            out[self.raw_key] = self.raw_array.crop(request[self.raw_key].roi)
        if self.labels_key in request:
            out[self.labels_key] = self.labels_array.crop(
                request[self.labels_key].roi)

        return out


class SaveBlockPosition(gp.BatchFilter):
    """Save offset and shape of a provided 2D array into non-spatial array for
    logging purposes.

    Args:

        raw (:class:`ArrayKey`):

            Data :class:`ArrayKey`, whose coordinates we log.

        log (:class:`ArrayKey`):

            Non-spatial :class:`ArrayKey` to store the coordinates.
    """

    def __init__(self, raw: gp.ArrayKey, log: gp.ArrayKey):

        self.raw = raw
        self.log = log

    def setup(self):

        self.provides(
            self.log,
            gp.ArraySpec(nonspatial=True)
        )

    def prepare(self, request):
        deps = gp.BatchRequest()
        deps[self.raw] = request[self.log].copy()
        return deps

    def process(self, batch, request):

        log = np.zeros((2, 2), dtype=int)
        roi = batch.arrays[self.raw].spec.roi
        log[0] = np.copy(roi.get_offset())
        log[1] = np.copy(roi.get_shape())

        logger.debug(f'Block offset and shape: {log}')

        batch = gp.Batch()
        batch[self.log] = gp.Array(
            log, gp.ArraySpec(nonspatial=True)
        )

        return batch


voxel_size = gp.Coordinate((1,) * 2)
input_size = gp.Coordinate((64,) * 2) * voxel_size

raw = gp.ArrayKey('RAW')
labels = gp.ArrayKey('LABELS')
log = gp.ArrayKey('LOG')

request = gp.BatchRequest()
request.add(raw, input_size)
request.add(labels, input_size)

request[log] = gp.ArraySpec(nonspatial=True)

pipeline = (
    Source(raw, labels, voxel_size)
    + SaveBlockPosition(
        raw=raw,
        log=log
    )

    + gp.RandomLocation()

    + gp.Reject(
        mask=labels,
        min_masked=0.05,
        reject_probability=0.9,
    )
)

with gp.build(pipeline) as p:
    for i in range(100):
        batch = p.request_batch(request)
        logger.info(
            f"Returned ROI with original offset and shape {batch[log].data}")
```

**Comment by pattonw** [comment]
Good catch. I missed this node when I was adding the random seed support.
I like you solution: `request._random_seed += random.randint(0, 2**63 - 1)`. As long as this is deterministic I think it will work as intended (and since we set the random seed at the start of the prepare method, it should be). Could you turn this into a pull request? If possible I would also appreciate a test showing that the random seeds are working as expected. I.e. repeating the same request from a pipeline with a `Reject` node provides the same results.

**Comment by benjamin9555** [comment]
Ok, I will draft a PR including a test for random seeding.
Regarding the tests, there seems to be quite some legacy from using `unittest`, while the new default testing framework is `pytest` now as far as I understand. I have also seen your efforts to standardize sources for the tests etc.
Would you mind writing up a short template/instruction list on how we would like to write new gunpowder tests?

**Comment by pattonw** [comment]
Sure, I'll work on something more formal and see if others agree, but for now here's what I try to follow:
1) write new tests in the `pytest` format. If you're updating a test that is written in `unittest`, feel free to change it to `pytest` or leave it as is.
2) Try not to make too many unique sources for each test. I added an `ArraySource` and a `GraphSource` in the `helper_sources.py` file that work pretty simply, just create an numpy array with the data you want, throw it in a `gp.Array` with whatever spec you want, and put it in an `ArraySource` with the key that you want. That should cover most cases so we don't have to keep making unique nodes per test, and can stick to only defining the unique data you want. If you need something that can't be satisfied this way, feel free to make a custom source (just don't name it `Test...`. If it begins with "test" `pytest` thinks it is callable and complains when it isn't).
3) Avoid randomness as much as possible. There are a lot of tests in there right now that repeat random behaviors 5k times or similar to check that desired behavior can occur. Now that we have baked in `random_seeds` in requests that shouldn't be necessary. If you see them I would greatly appreciate them being rewritten into more deterministic tests (as they are they make running tests quite slow). Ideally doing something like guaranteeing the behavior you want as is the case with [simple augments tests](https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/tests/cases/simple_augment.py#L48). Not all nodes with randomness support this though. In those cases, adding support for manually defining probabilities would be ideal, but writing tests to work with the existing implementation is fine too.

**Comment by pattonw** [comment]
This has been resolved
