### ISSUE TITLE
random seed bug in stack node

### ISSUE THREAD

**Issue by abred** [funkelab/gunpowder#161]
The stack node copies the request and calls `provide`:
https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/gunpowder/nodes/batch_provider.py#L184-L188

In `provide` `request_batch` is called for each element in the batch;
https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/gunpowder/nodes/stack.py#L28-L31
In `request_batch` the random seed is updated, once for each element, so at the end it is `batch_size` steps further:
https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/gunpowder/nodes/batch_provider.py#L176

So far everything is fine. The problem is in the following iterations. When a new batch is requested, the random seed of the original request is advanced only once. Therefore when it is back at the stack node it has the same state as after the first element of the batch of the previous iteration. Thus the first `batch_size-1` elements in the second iteration are the same as the last `batch_size-1` elements of the first iteration, and so on, it shifts by one in every iteration.
I hope this description makes somewhat sense.

**Comment by pattonw** [comment]
this has been solved
