### ISSUE TITLE
Duplicated loop

### ISSUE THREAD

**Issue by rhoadesScholar** [funkelab/gunpowder#171]
Loops beginning on https://github.com/funkey/gunpowder/blob/03d15ee0dcd63e1250f851f108c487fff30a473a/gunpowder/torch/nodes/train.py#L265
and https://github.com/funkey/gunpowder/blob/03d15ee0dcd63e1250f851f108c487fff30a473a/gunpowder/torch/nodes/train.py#L289 are duplicates.

**Comment by pattonw** [comment]
solved here: https://github.com/funkelab/gunpowder/commit/ec88b0cd8ebe9a6b44f8f08680b42066f03594eb
