### ISSUE TITLE
AddAffinities node casts labels to np.int32, why?

### ISSUE THREAD

**Issue by yajivunev** [funkelab/gunpowder#175]
AddAffinities node does this:
```
affinities = seg_to_affgraph(
            batch.arrays[self.labels].data.astype(np.int32),
            self.affinity_neighborhood
).astype(self.dtype)
```

and in seg_to_affgraph:
```
aff = np.zeros((nEdge,)+shape,dtype=np.int32)
```
which gives empty affs if labels has really big uint64 values, which it might. is there a reason why labels is cast such a way? it seems to work alright if i change the type cast to np.uint64

thanks!

**Comment by pattonw** [comment]
fixed in patch 1-3-3
