### ISSUE TITLE
ZarrSource doesn't support Stores

### ISSUE THREAD

**Issue by mzouink** [funkelab/gunpowder#184]
Current Gunpowder ask for Zarr path in order to get the data. Which limite the use cases.
E.g:
- Remote data 
- A new Zarr Store

I think it will be more useful to have Zarr Store input instead of Zarr Path https://github.com/funkey/gunpowder/blob/773b5578b01d16d34ef3cc466904ab876bba8bf1/gunpowder/ext/zarr_file.py#L11
And relay on Zarr to provide the data

@funkey

**Comment by pattonw** [comment]
it does now, thanks Marwan :)
