### ISSUE TITLE
Passing cuda device as an argument to Train, Predict nodes

### ISSUE THREAD

**Issue by Mohinta2892** [funkelab/gunpowder#188]
It would be helpful if we could pass a cuda device explicitly to the train and predict nodes for DGX systems, to be able to spawn multiple models on different cards simultaneously on a single machine.
Currently both scripts default to "cuda:0" on device availability: "cuda:0"

I have added this into a fork of the repo, wanted to discuss if this is something useful to integrate here.

Best,
Samia

**Comment by pattonw** [comment]
Yes, this would be quite helpful to integrate into gunpowder directly

**Comment by Mohinta2892** [comment]
Thanks for replying Will!
I shall raise a pull request soon-ish.

**Comment by pattonw** [comment]
solved in a pull request
