### ISSUE TITLE
SpecifiedLocation Stuck in Infinite Loop

### ISSUE THREAD

**Issue by moenigin** [funkelab/gunpowder#201]
Hi,

Testing augmentation nodes on my data I ran into an issue with the SpecifiedLocation node: When the requested ROI is not contained in the data from any of the locations provided SpecifiedLocation gets stuck in an [infinite loop](https://github.com/funkelab/gunpowder/blob/main/gunpowder/nodes/specified_location.py#L82).

This reproduces the issue:
``` 
import gunpowder as gp
import numpy as np
import zarr

if __name__ == '__main__':
    dummy_data = np.random.random((4, 4))
    f = zarr.open('dummy.zarr', 'w')
    f['raw'] = dummy_data

    raw = gp.ArrayKey('RAW')
    source = gp.ZarrSource(
        'dummy.zarr',
        {raw: 'raw'},
        {raw: gp.ArraySpec(
            voxel_size=(1, 1),
            interpolatable=True)}
    )
    pipeline = source + gp.SpecifiedLocation([(3, 3), (0, 0)])
    # + gp.SpecifiedLocation([(0, 0)])

    dummy_request = gp.BatchRequest()
    dummy_request.add(raw, (3, 3), (1, 1))

    with gp.build(pipeline):
        batch = pipeline.request_batch(dummy_request)
```

I am unsure what the best approach would be to avoid this -  whether to check all locations beforehand and raise an error if none contains the requested roi or to tag locations already checked for a given request so that [this](https://github.com/funkelab/gunpowder/blob/main/gunpowder/nodes/specified_location.py#L127) does not reset to the first location.
Thanks for your feedback,
Nila

**Comment by pattonw** [comment]
I would guess best practice here would be to pad your raw data with 0s. This would allow your specified locations to be sampled, even if the distance between your location to the edge of your data is less than the radius of your requested batch.

But regardless there should be a better error message and we should not end up in an infinite loop. I've merged a loop counter into patch-v1.3.3 that checks to see if we loop through every potential location and errors if we do.
