### ISSUE TITLE
z5py-based tests don't run on CI

### ISSUE THREAD

**Issue by clbarnes** [funkelab/gunpowder#30]
As discussed in https://github.com/funkey/gunpowder/pull/29

z5py has a runtime dependency on some GCC-related libraries which are more recent than those available on conda and travis. More recent systems don't seem to have this issue. It is difficult to trigger this issue in a minimal test case like https://github.com/clbarnes/z5_boost_bug , but may be resolved by future updates to z5py, travis, conda, or gunpowder.

**Comment by pattonw** [comment]
This doesn't seem to be a problem anymore
