### ISSUE TITLE
node_dependencies batch_id

### ISSUE THREAD

**Issue by pattonw** [funkelab/gunpowder#74]
The node_dependencies branch contains a crop and merge step for batches at the end of the provide function of a BatchFilter. This leads to a new Batch being created and returned with a new batch_id.
If a pipeline gets long, or is run by many threads in parallel, it seems like the batch_id will be incremented excessively and the over head of retrieving a lock could become significant.

One option to resolve this that seems quite nice is to replace the batch_id with a request_id since that should be more consistent and useful for grouping batches that belong together.

**Comment by funkey** [comment]
Catching up on this issue. This is a nice idea, I think we should do it. Do you want to send a PR?

**Comment by pattonw** [comment]
Yes, would this be a good way of implementing a request id?
We could move the `__next_id` variable from `Batch` to the new `Pipeline` class. Every time you `request_batch` it could set a request_id and increment the `__next_id`.
`BatchProvider` would handle copying the id on merge/crop, to avoid making users set the id when they create a new request or batch.

As far as I can tell, the batch_id is only used for logging which should not be easier to interpret after this change, and as a possible argument the snapshot file name. If there are multiple snapshot nodes in a pipeline and the snapshot file is identified only by id, this change would lead to snapshot files getting overwritten.
