### ISSUE TITLE
Seeded batch request randomness

### ISSUE THREAD

**Issue by funkey** [funkelab/gunpowder#9]
Have batch requests carry a seed, used to draw random numbers, such that requesting the same batch with the same seed two times results in exactly the same outcome.

This facilitates testing, debugging, and "peeking": Nodes like `Reject` can have a "peek" at what a part of a batch would look like by requesting a subset of the batch. On acceptance, they can request the rest. This requires that multiple requests are equally randomized.

**Comment by nilsec** [comment]
This would be great. What is the purpose of peeking in this context? I am asking because I would be interested in this feature and I did something like that for ```DefectAugment``` so maybe I can have a look. The peek part is not clear to me though.

**Comment by funkey** [comment]
The peeking would be more efficient. Instead of requesting a complete batch, `Reject` could request only the foreground mask. Only if the mask meets the `min_masked` criteria, it would request the remaining parts of the batch. This works only if repeated requests to randomized upstream providers are seeded in the same way.

**Comment by hanslovsky** [comment]
Is that going to be part of 1.0?

**Comment by funkey** [comment]
I think we will release 1.0 independently. This enhancement will not (should not) break the existing API, so it can be added in a later release, if needed.

**Comment by pattonw** [comment]
done
